#!/bin/sh
#-------------------------------------------------------------------------
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
#-------------------------------------------------------------------------
#
# Regenerate core_sources.txt.
#
# Meson does not glob, on purpose: a source list that a build reads from the
# filesystem hides an added or removed file from review.  So the list is a
# checked-in file, and this script is how it is refreshed after a merge from
# apache/cloudberry that adds or removes an ORCA source.
#
#     sh pg19/orca/list-core-sources.sh > pg19/orca/core_sources.txt
#
# Run it from the top of the tree.

set -eu

G=src/backend/gporca

if [ ! -d "$G/libgpos/src" ]; then
	echo "run this from the top of the Cloudberry tree" >&2
	exit 1
fi

cat <<'HEADER'
# ORCA's four core libraries, compiled from Cloudberry's tree where they lie.
# Generated by pg19/orca/list-core-sources.sh; paths are relative to pg19/orca/.
#
# These files carry no PostgreSQL dependency at all -- checked: none of the
# 2,076 files under them includes a PostgreSQL header -- so they are the same
# code on PostgreSQL 19 as on Cloudberry's PostgreSQL 16, and the port takes
# them unmodified.  That is what keeps Cloudberry's own ORCA features (plan
# hints, parallel scans, the dedup-superset preprocessor, partial aggregation
# below joins) without porting a line of them.
HEADER

find "$G/libgpos/src" "$G/libnaucrates/src" "$G/libgpopt/src" "$G/libgpdbcost/src" \
	-name '*.cpp' | sort | sed 's|^|../../|'
