#!/usr/bin/env python3
#-------------------------------------------------------------------------
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
#-------------------------------------------------------------------------
#
# catalog_json.py <system_fk_info.h> <catversion.h>: the catalog's foreign
# keys as gpcheckcat reads them (gppylib/gpcatalog.py), in the JSON
# Cloudberry's src/backend/catalog/process_foreign_keys.pl writes:
#
#     { "__comment": ..., "__info": { "CATALOG_VERSION_NO": "..." },
#       "<catalog>": { "foreign_keys": [ [ ["<column>"], "<catalog>", ["<column>"] ], ... ] }, ... }
#
# Cloudberry declares them in its headers, FOREIGN_KEY(col REFERENCES
# cat(col)) lines, one column each.  PostgreSQL 19 marks them with
# BKI_LOOKUP and DECLARE_FOREIGN_KEY, and genbki.pl writes them all into
# system_fk_info.h, which pg_get_catalog_foreign_keys() serves: a line
#
#     { /* pg_proc */ 1255, /* pg_namespace */ 2615, "{pronamespace}", "{oid}", false, false},
#
# a key.  The keys of one column that is not an array are taken, the ones
# gpcheckcat's query compares a column with a column by (a key of several
# columns, pg_attrdef's to pg_attribute, or of an array's elements,
# pg_proc.proargtypes, is none it can ask about); a key whose column may be
# 0 is taken too, as gpcheckcat leaves 0 out.

import json
import re
import sys

KEY = re.compile(r'\{\s*/\*\s*(\w+)\s*\*/\s*\d+,\s*/\*\s*(\w+)\s*\*/\s*\d+,\s*'
                 r'"\{([^}]*)\}",\s*"\{([^}]*)\}",\s*(true|false),\s*(true|false)\s*\}')
VERSION = re.compile(r'^#define\s+CATALOG_VERSION_NO\s+(\d+)', re.M)


def main(fk_info, catversion):
    with open(catversion) as f:
        m = VERSION.search(f.read())
    catalogs = {}
    with open(fk_info) as f:
        for fktable, pktable, fkcols, pkcols, is_array, _ in KEY.findall(f.read()):
            fkcols = fkcols.split(',')
            pkcols = pkcols.split(',')
            if len(fkcols) != 1 or is_array == 'true':
                continue
            keys = catalogs.setdefault(fktable, {'foreign_keys': []})['foreign_keys']
            keys.append([fkcols, pktable, pkcols])

    # laid out as process_foreign_keys.pl lays it out: a line a key
    print('{')
    print('   "__comment" : "Generated by catalog_json.py from system_fk_info.h",')
    sys.stdout.write('   "__info" : { "CATALOG_VERSION_NO" : %s }'
                     % json.dumps(m.group(1) if m else 'unknown'))
    for name in sorted(catalogs):
        print(',')
        print('   %s : {' % json.dumps(name))
        print('      "foreign_keys" : [')
        print(',\n'.join('         [ %s, %s, %s ]' % tuple(json.dumps(x) for x in key)
                         for key in catalogs[name]['foreign_keys']))
        print('      ]')
        sys.stdout.write('   }')
    print()
    print('}')


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
